apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-file
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
data:
{{- with .Values.config.override.logging.application }}
  logging-application: | {{ . | nindent 4 }}
{{- end }}
