apiVersion: v2

name: ${helm.prefix}
description: ${helm.prefix}

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"

dependencies:

  - name: ${helm.prefix}-rediscluster
    version: ${helm.chart.version}
    alias: edusharing_rediscluster
    condition: edusharing_rediscluster.enabled

  - name: ${helm.prefix}-repository
    version: ${helm.chart.version}
    alias: edusharing_repository
    condition: edusharing_repository.enabled

  - name: ${helm.prefix}-postgresql
    version: ${helm.chart.version}
    alias: edusharing_repository_postgresql
    condition: edusharing_repository_postgresql.enabled

  - name: ${helm.prefix}-rediscluster
    version: ${helm.chart.version}
    alias: edusharing_repository_rediscluster
    condition: edusharing_repository_rediscluster.enabled

  - name: ${helm.prefix}-repository-search-solr
    version: ${helm.chart.version}
    alias: edusharing_repository_search_solr
    condition: edusharing_repository_search_solr.enabled

  - name: ${helm.prefix}-repository-service
    version: ${helm.chart.version}
    alias: edusharing_repository_service
    condition: edusharing_repository_service.enabled
