variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MAVEN_CLI: "-Ddocker.registry=$DOCKER_REGISTRY -Dhelm.deploy.url=$HELM_REGISTRY -Dhelm.deploy.type=$HELM_TYPE -Dmaven.deploy.releases=$MAVEN_DEPLOY_RELEASES -Dmaven.deploy.snapshots=$MAVEN_DEPLOY_SNAPSHOTS --batch-mode --errors --fail-fast --show-version -T 1C"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

default:
  image: maven:3.8.4-jdk-11

stages:
  - test
  - deploy

deploy:
  stage: deploy
  needs: []
  script:
    - mvn $MAVEN_CLI -s .mvn/settings.xml deploy

.frontend_job: &frontend_job
  variables:
    NODE_VERSION: 16
  image: node:$NODE_VERSION
  cache:
    key:
      files:
        - Frontend/package-lock.json
      prefix: node-modules-$NODE_VERSION  
    paths:
      - Frontend/node_modules
  before_script:
    - cd Frontend
    # Install dependencies on cache miss, e.g., when first running on a ci runner.
    - ([[ -d node_modules ]] || npm ci)

# build:
#   <<: *frontend_job
#   stage: build
#   script:
#     - npm run build

check formatting:
  <<: *frontend_job
  stage: test
  needs: []
  script:
    - npm run check:format

check linting:
  <<: *frontend_job
  stage: test
  needs: []
  script:
    - npm run check:lint

# e2e:
#   <<: *frontend_job
#   stage: test
#   needs: []
#   image: mcr.microsoft.com/playwright:v1.22.0-focal
#   variables:
#     NODE_VERSION: 16  # Matches the preinstalled version of node in the image.
#     # Test against external frontend.
#     # E2E_TEST_BASE_URL: http://192.168.16.171/edu-sharing/ 
#     BACKEND_URL: http://192.168.16.171
#   script:
#     - node -v
#     - npm -v
#     - npm start &
#     - sleep 120
#     - npm run e2e
#   artifacts:
#     paths:
#       - Frontend/playwright-report/
#     when: on_failure